package ecommerce.orderprocessing;
import ecommerce.authentification.Customer;
import java.util.Date;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Scanner;

import ecommerce.productmanagement.Product;
import ecommerce.shoppingcart.*;
public class Order {
    private int orderId;
    private Customer customer;
    private String shippingAddress;
    private String shippingDate;
    private String orderStatus;
    private LocalDate orderDate;
    private HashMap<Product,Integer> listOfProducts;

    private double totalAmount;

    public String getShippingDate() {
        return shippingDate;
    }

    public String getOrderStatus() {
        return orderStatus;
    }

    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    public HashMap<Product, Integer> getListOfProducts() {
        return listOfProducts;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public void setShippingDate(String shippingDate) {
        this.shippingDate = shippingDate;
    }

    //constructor with user input (the id is generated by the order manager)
    public Order(Customer customer,int orderId)
    {
        ShoppingCart shoppingCart=customer.getShoppingCart();
        //when the order is passed automatocally it get's today's date
        orderDate=LocalDate.now();
        //add the shipping cost i supposed here that every product is delievred for 2 dinars
        totalAmount=shoppingCart.getTotalPrice()+shoppingCart.getListOfProducts().size()*2;
        orderStatus="New";
        shippingAddress=customer.getShippingAddress();
        listOfProducts=shoppingCart.getListOfProducts();
    }
    public void showOrderDetails() {
        System.out.println("Order Details:");
        System.out.println("Order Date: " + orderDate);
        System.out.println("Customer: " + customer.getUserName());
        System.out.println("Shipping Address: " + shippingAddress);
        System.out.println("Shipping Date: " + shippingDate);
        System.out.println("Order Status: " + orderStatus);
        System.out.println("Total Amount: $" + totalAmount);

        System.out.println("List of Products:");
        for (Product product : listOfProducts.keySet()) {
            int quantity = listOfProducts.get(product);
            System.out.println( product.getName() + "(Qunatity: " + quantity + ")");
        }
    }
    public double getTotalAmount() {
        return totalAmount;
    }

    public int getOrderId() {
        return orderId;
    }
}